### PR TITLE
changed script for music.html

### PR DESCRIPTION
**Pull request by BeryllN**

### CODE REVIEW

**Comment by jakecoffman** [comment]
Instead of creating music2.html can you just edit music.html to your version? 

You can push to your branch and this PR will update.

**Comment by BeryllN** [comment]
Sorry :/
I found it now :)

**Comment by jakecoffman** [comment]
thanks!

**Comment by jakecoffman** [comment]
closes #3

**Comment by BeryllN** [comment]
you're welcome!

i'm most grateful for your tutorials, they are very clear and really helped a lot! :)

**Pull request merged**
